import type { NextPage } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

const Home: NextPage = () => {
  const lol = '';

  return (
    <>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Lets gooooooooooooo</h1>
        <Link href="watches">Watches</Link>
      </main>
    </>
  );
};

export default Home;
