import client from '@/apollo/client';
import { Text } from '@/components/common/Text/Text';
import { KeyFeatureProps, KeyFeatures } from '@/components/product/KeyFeatures/KeyFeatures';
import { ProductFragment } from '@/fragments/product/product.generated';
import {
  GetProductDocument,
  GetProductQuery,
  GetProductQueryVariables,
} from '@/queries/getProduct/getProduct.generated';
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { ParsedUrlQuery } from 'querystring';

const features: KeyFeatureProps[] = [
  {
    id: '001',
    type: 'IP_RATING',
    label: 'Case material',
    value: 'Stainless steel',
  },
  {
    id: '002',
    type: 'DIAMETER',
    label: 'Water resistance',
    value: '10 bars i',
  },
  {
    id: '003',
    type: 'THICKNESS',
    label: 'Diameter',
    value: '41.0 mm',
  },
  {
    id: '004',
    type: 'WEIGHT',
    label: 'Thickness',
    value: '13.3 mm mm',
  },
  {
    id: '005',
    type: 'BATTERY_LIFE',
    label: 'Product Weight (Approx.)',
    value: '99.0 g.',
  },
  {
    id: '006',
    type: 'MATERIAL',
    label: 'Power reserve',
    value: 'Approx. 70 hrs',
  },
];

type WatchPageQuery = ParsedUrlQuery & {
  watchId?: string;
};

export const Watch: NextPage<{ watch: ProductFragment & { features: KeyFeatureProps[] } }> = ({ watch }) => {
  return (
    <>
      <Head>
        <title>Watch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Watch {watch?.id}</h1>
        <Text preserveWhitespace>
          {`I'm baby thundercats neutra williamsburg hot chicken cliche, vaporware bodega boys pitchfork. Distillery squid roof party bitters mukbang. Williamsburg mustache coloring book tilde keffiyeh narwhal hot chicken kombucha cray bruh. Ramps tumeric bodega boys, hexagon seitan street art bespoke. Affogato gluten-free distillery jean shorts, activated charcoal vinyl bespoke. Neutra brunch food truck chartreuse kickstarter. Tofu activated charcoal selfies, YOLO JOMO kogi health goth.\n\nPut a bird on it brunch raw denim intelligentsia chicharrones. Meh hexagon bushwick, mumblecore leggings shoreditch DIY 90's. Readymade same snackwave kitsch four loko synth, iceland chillwave copper mug raclette lyft ennui. Slow-carb gatekeep lo-fi DSA 90's shoreditch heirloom, scenester stumptown narwhal. 3 wolf moon adaptogen schlitz vaporware hoodie pug.`}
        </Text>

        {watch?.media?.map(
          (media) =>
            media.type === 'IMAGE' && (
              <Image priority key={media.id} alt="" src={media.url ?? ''} width={520} height={520} />
            )
        )}

        <KeyFeatures features={watch.features} />

        <Link href="/">Home</Link>
        <Link href="/watches">Watches</Link>
      </main>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  // Empty paths as there are thousands of products so we'll generate on first access.
  return {
    paths: [],
    fallback: 'blocking',
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  // We know the ID is the first segment when split.
  const watchId = (params?.watchId as string)?.split('-')[0];

  try {
    const { data, errors } = await client.query<GetProductQuery, GetProductQueryVariables>({
      query: GetProductDocument,
      variables: {
        id: watchId,
      },
    });

    if (!data || errors) {
      return {
        notFound: true,
      };
    }

    return {
      props: {
        watch: {
          ...data.product,
          // These would come from API.
          features,
        },
      },
    };
  } catch {
    return {
      notFound: true,
    };
  }
};

export default Watch;
