import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

export const Watches: NextPage<{}> = () => {
  return (
    <>
      <Head>
        <title>Watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Watches</h1>
        <Link href="/">Home</Link>
        <Link href="watches/test-id">Watch</Link>
      </main>
    </>
  );
};

export default Watches;
