import { ProductCard } from '@/components/common/ProductCard/ProductCard';
import { useGetProductsQuery } from '@/queries/getProducts/getProducts.generated';
import { kebabCase } from 'lodash';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useCallback, useState } from 'react';
import { WatchesCardGrid } from './Index.styles';

export const Watches: NextPage<{}> = () => {
  const router = useRouter();

  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState([]);

  const {
    data,
    loading: dataLoading,
    networkStatus,
    refetch,
    fetchMore,
  } = useGetProductsQuery({
    notifyOnNetworkStatusChange: true,
    variables: {
      filterSearch: search,
      filterType: filter,
    },
  });

  const handleLoadMoreClick = useCallback(() => {
    console.log(data?.products?.pageInfo?.endCursor);
    fetchMore({
      variables: {
        after: data?.products?.pageInfo?.endCursor,
      },
    });
  }, [fetchMore, data?.products?.pageInfo?.endCursor]);
  console.log(data);

  return (
    <>
      <Head>
        <title>Watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Watches</h1>

        {!!data?.products?.edges?.length && (
          <div>
            <WatchesCardGrid>
              {data.products.edges.map(({ node: product }, index) => (
                <ProductCard
                  key={product.id}
                  href={`/watches/${encodeURIComponent(`${product.id}-${kebabCase(product.name)}`)}`}
                >
                  {product?.thumbnail?.url && (
                    <div style={{ position: 'relative', aspectRatio: '16 / 9' }}>
                      <Image src={product.thumbnail.url} alt="" fill />
                    </div>
                  )}

                  <h3 style={{ wordWrap: 'break-word' }}>
                    {product.name} ({index}) {product.productType.id}
                  </h3>
                  <p>{product.description}</p>
                </ProductCard>
              ))}
            </WatchesCardGrid>

            <div style={{ padding: '32px' }}>
              <button
                type="button"
                disabled={!data?.products?.pageInfo?.hasNextPage ?? true}
                onClick={handleLoadMoreClick}
              >
                Load more
              </button>
            </div>
          </div>
        )}

        <Link href="/">Home</Link>
        <Link href="watches/UHJvZHVjdDoxNTQ=">Watch</Link>
      </main>
    </>
  );
};

export default Watches;
